name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Adjust based on pyproject.toml

      - name: Install Poetry
        run: |
          pip install poetry==1.8.5
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Cache Poetry virtualenv
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        run: |
          poetry install

#      - name: Run mypy (static type checking)
#        run: poetry run mypy .

      - name: Run unit tests with coverage
        run: |
          poetry run pytest tests/* --asyncio-mode=auto --cov=redisaq --cov-report=xml:unit_coverage.xml

      - name: Upload unit test coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./unit_coverage.xml
          flags: unittests
          fail_ci_if_error: true
